ha:
  mac: '20:f8:3b:0:76:f5'
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjMmI4NGU5MWJhZWQ0ZGZhODQ4NmVlNzVlN2QwOWE5NyIsImlhdCI6MTcyNjQyNDM3NywiZXhwIjoyMDQxNzg0Mzc3fQ.X7xQolQR5QzXXzISyGRd9OCzvyb5jnbgWNW7zcuEXb8
